"""C3 template layout — Template TWB Swap approach.

Uses the EXACT XML from the professional Tableau Dashboard Layout Templates
c.3 template. The XML was generated by Tableau Desktop and is guaranteed valid.

Strategy: Copy the template XML verbatim, then surgically swap text placeholder
zones with real worksheet/filter zones. Never touch coordinates or structure.
"""

from __future__ import annotations

import logging
from copy import deepcopy
from typing import Any, Callable

from lxml import etree

logger = logging.getLogger(__name__)

# ── The exact C3 template XML from Tableau Desktop ──────────────────────
# This XML was extracted from "Tableau Dashboard Layout Templates.twbx"
# dashboard "c.3". Every coordinate, margin, and style is Tableau-native.
_C3_TEMPLATE_XML = """\
<zones>
  <zone h="100000" id="1" param="vert" type-v2="layout-flow" w="100000" x="0" y="0">
    <zone fixed-size="70" h="8750" id="2" is-fixed="true" param="horz" type-v2="layout-flow" w="100000" x="0" y="0">
      <zone forceUpdate="true" h="8750" id="5" type-v2="text" w="98666" x="667" y="0">
        <formatted-text>
          <run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="20">TITLE PLACEHOLDER</run>
        </formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/>
          <format attr="border-style" value="none"/>
          <format attr="border-width" value="0"/>
          <format attr="margin" value="4"/>
        </zone-style>
      </zone>
      <zone-style>
        <format attr="border-color" value="#000000"/>
        <format attr="border-style" value="none"/>
        <format attr="border-width" value="0"/>
        <format attr="margin-right" value="8"/>
        <format attr="margin-left" value="8"/>
        <format attr="background-color" value="#ffffff"/>
      </zone-style>
    </zone>
    <zone fixed-size="30" h="3750" id="3" is-fixed="true" param="horz" type-v2="layout-flow" w="100000" x="0" y="8750">
      <zone forceUpdate="true" h="3750" id="8" type-v2="text" w="98666" x="667" y="8750">
        <formatted-text>
          <run bold="true" fontalignment="1" fontcolor="#ffffff" fontsize="12">FILTERS PLACEHOLDER</run>
        </formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/>
          <format attr="border-style" value="none"/>
          <format attr="border-width" value="0"/>
          <format attr="margin" value="4"/>
        </zone-style>
      </zone>
      <zone-style>
        <format attr="border-color" value="#000000"/>
        <format attr="border-style" value="none"/>
        <format attr="border-width" value="0"/>
        <format attr="margin-right" value="8"/>
        <format attr="margin-left" value="8"/>
        <format attr="background-color" value="#192f3e"/>
      </zone-style>
    </zone>
    <zone fixed-size="100" h="12500" id="16" is-fixed="true" layout-strategy-id="distribute-evenly" param="horz" type-v2="layout-flow" w="100000" x="0" y="12500">
      <zone forceUpdate="true" h="12500" id="17" type-v2="text" w="20000" x="0" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_1</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="4"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="8"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="20" type-v2="text" w="20000" x="20000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_2</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="4"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="4"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="21" type-v2="text" w="20000" x="40000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_3</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="4"/><format attr="margin-top" value="0"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="19" type-v2="text" w="20000" x="60000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_4</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="4"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="4"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="18" type-v2="text" w="20000" x="80000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_5</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="8"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="4"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone-style>
        <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
        <format attr="margin" value="0"/><format attr="margin-top" value="0"/>
      </zone-style>
    </zone>
    <zone fixed-size="1100" h="75000" id="9" is-fixed="true" layout-strategy-id="distribute-evenly" param="horz" type-v2="layout-flow" w="100000" x="0" y="25000">
      <zone h="75000" id="10" layout-strategy-id="distribute-evenly" param="vert" type-v2="layout-flow" w="50000" x="0" y="25000">
        <zone forceUpdate="true" h="37500" id="12" type-v2="text" w="50000" x="0" y="25000">
          <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_1</run></formatted-text>
          <zone-style>
            <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
            <format attr="margin" value="4"/><format attr="margin-left" value="8"/>
            <format attr="background-color" value="#ffffff"/>
          </zone-style>
        </zone>
        <zone forceUpdate="true" h="37500" id="13" type-v2="text" w="50000" x="0" y="62500">
          <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_3</run></formatted-text>
          <zone-style>
            <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
            <format attr="margin" value="4"/><format attr="margin-bottom" value="8"/><format attr="margin-left" value="8"/>
            <format attr="background-color" value="#ffffff"/>
          </zone-style>
        </zone>
      </zone>
      <zone h="75000" id="11" layout-strategy-id="distribute-evenly" param="vert" type-v2="layout-flow" w="50000" x="50000" y="25000">
        <zone forceUpdate="true" h="37500" id="14" type-v2="text" w="50000" x="50000" y="25000">
          <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_2</run></formatted-text>
          <zone-style>
            <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
            <format attr="margin" value="4"/><format attr="margin-right" value="8"/>
            <format attr="background-color" value="#ffffff"/>
          </zone-style>
        </zone>
        <zone forceUpdate="true" h="37500" id="15" type-v2="text" w="50000" x="50000" y="62500">
          <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_4</run></formatted-text>
          <zone-style>
            <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
            <format attr="margin" value="4"/><format attr="margin-right" value="8"/><format attr="margin-bottom" value="8"/>
            <format attr="background-color" value="#ffffff"/>
          </zone-style>
        </zone>
      </zone>
    </zone>
  </zone>
</zones>
"""

# ── The C2 template — 4 KPIs, no 5th slot ─────────────────────────────
# Extracted from "Tableau Dashboard Layout Templates.twbx" dashboard "c.2".
# Same professional styling, but only 4 KPI slots (25% width each).
# Better when the dashboard has ≤4 KPI metrics.
_C2_TEMPLATE_XML = """\
<zones>
  <zone h="100000" id="1" param="vert" type-v2="layout-flow" w="100000" x="0" y="0">
    <zone fixed-size="70" h="8750" id="2" is-fixed="true" param="horz" type-v2="layout-flow" w="100000" x="0" y="0">
      <zone forceUpdate="true" h="8750" id="5" type-v2="text" w="98666" x="667" y="0">
        <formatted-text>
          <run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="20">TITLE PLACEHOLDER</run>
        </formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="4"/>
        </zone-style>
      </zone>
      <zone-style>
        <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
        <format attr="margin-right" value="8"/><format attr="margin-left" value="8"/>
        <format attr="background-color" value="#ffffff"/>
      </zone-style>
    </zone>
    <zone fixed-size="30" h="3750" id="3" is-fixed="true" param="horz" type-v2="layout-flow" w="100000" x="0" y="8750">
      <zone forceUpdate="true" h="3750" id="8" type-v2="text" w="98666" x="667" y="8750">
        <formatted-text>
          <run bold="true" fontalignment="1" fontcolor="#ffffff" fontsize="12">FILTERS PLACEHOLDER</run>
        </formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="4"/>
        </zone-style>
      </zone>
      <zone-style>
        <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
        <format attr="margin-right" value="8"/><format attr="margin-left" value="8"/>
        <format attr="background-color" value="#192f3e"/>
      </zone-style>
    </zone>
    <zone fixed-size="100" h="12500" id="16" is-fixed="true" layout-strategy-id="distribute-evenly" param="horz" type-v2="layout-flow" w="100000" x="0" y="12500">
      <zone forceUpdate="true" h="12500" id="17" type-v2="text" w="25000" x="0" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_1</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="4"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="8"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="20" type-v2="text" w="25000" x="25000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_2</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="4"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="4"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="19" type-v2="text" w="25000" x="50000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_3</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="4"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="4"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="18" type-v2="text" w="25000" x="75000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_4</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="8"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="4"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone-style>
        <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
        <format attr="margin" value="0"/><format attr="margin-top" value="0"/>
      </zone-style>
    </zone>
    <zone fixed-size="1100" h="75000" id="9" is-fixed="true" layout-strategy-id="distribute-evenly" param="horz" type-v2="layout-flow" w="100000" x="0" y="25000">
      <zone h="75000" id="10" layout-strategy-id="distribute-evenly" param="vert" type-v2="layout-flow" w="50000" x="0" y="25000">
        <zone forceUpdate="true" h="37500" id="12" type-v2="text" w="50000" x="0" y="25000">
          <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_1</run></formatted-text>
          <zone-style>
            <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
            <format attr="margin" value="4"/><format attr="margin-left" value="8"/>
            <format attr="background-color" value="#ffffff"/>
          </zone-style>
        </zone>
        <zone forceUpdate="true" h="37500" id="13" type-v2="text" w="50000" x="0" y="62500">
          <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_3</run></formatted-text>
          <zone-style>
            <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
            <format attr="margin" value="4"/><format attr="margin-bottom" value="8"/><format attr="margin-left" value="8"/>
            <format attr="background-color" value="#ffffff"/>
          </zone-style>
        </zone>
      </zone>
      <zone h="75000" id="11" layout-strategy-id="distribute-evenly" param="vert" type-v2="layout-flow" w="50000" x="50000" y="25000">
        <zone forceUpdate="true" h="37500" id="14" type-v2="text" w="50000" x="50000" y="25000">
          <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_2</run></formatted-text>
          <zone-style>
            <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
            <format attr="margin" value="4"/><format attr="margin-right" value="8"/>
            <format attr="background-color" value="#ffffff"/>
          </zone-style>
        </zone>
        <zone forceUpdate="true" h="37500" id="15" type-v2="text" w="50000" x="50000" y="62500">
          <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_4</run></formatted-text>
          <zone-style>
            <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
            <format attr="margin" value="4"/><format attr="margin-right" value="8"/><format attr="margin-bottom" value="8"/>
            <format attr="background-color" value="#ffffff"/>
          </zone-style>
        </zone>
      </zone>
    </zone>
  </zone>
</zones>
"""

# ── C4 template — Logo + Title, 4 KPIs, 1 full-width + 2 half-width sheets ──
# Layout from Image 3: professional template with logo placeholder.
# Structure: Logo|Title → Filters → 4 KPIs → 1 full-width chart → 2 side-by-side charts
_C4_TEMPLATE_XML = """\
<zones>
  <zone h="100000" id="1" param="vert" type-v2="layout-flow" w="100000" x="0" y="0">
    <zone fixed-size="70" h="8750" id="2" is-fixed="true" param="horz" type-v2="layout-flow" w="100000" x="0" y="0">
      <zone forceUpdate="true" h="8750" id="6" type-v2="text" w="15000" x="0" y="0">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="12">LOGO PLACEHOLDER</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#d0d0d0"/><format attr="border-style" value="solid"/><format attr="border-width" value="1"/>
          <format attr="margin" value="4"/><format attr="margin-left" value="8"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="8750" id="5" type-v2="text" w="83666" x="15000" y="0">
        <formatted-text>
          <run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="20">TITLE PLACEHOLDER</run>
        </formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="4"/>
        </zone-style>
      </zone>
      <zone-style>
        <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
        <format attr="margin-right" value="8"/><format attr="margin-left" value="8"/>
        <format attr="background-color" value="#ffffff"/>
      </zone-style>
    </zone>
    <zone fixed-size="30" h="3750" id="3" is-fixed="true" param="horz" type-v2="layout-flow" w="100000" x="0" y="8750">
      <zone forceUpdate="true" h="3750" id="8" type-v2="text" w="98666" x="667" y="8750">
        <formatted-text>
          <run bold="true" fontalignment="1" fontcolor="#ffffff" fontsize="12">FILTERS PLACEHOLDER</run>
        </formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="4"/>
        </zone-style>
      </zone>
      <zone-style>
        <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
        <format attr="margin-right" value="8"/><format attr="margin-left" value="8"/>
        <format attr="background-color" value="#192f3e"/>
      </zone-style>
    </zone>
    <zone fixed-size="100" h="12500" id="16" is-fixed="true" layout-strategy-id="distribute-evenly" param="horz" type-v2="layout-flow" w="100000" x="0" y="12500">
      <zone forceUpdate="true" h="12500" id="17" type-v2="text" w="25000" x="0" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_1</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="4"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="8"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="20" type-v2="text" w="25000" x="25000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_2</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="4"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="4"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="19" type-v2="text" w="25000" x="50000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_3</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="4"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="4"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="18" type-v2="text" w="25000" x="75000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_4</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="8"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="4"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone-style>
        <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
        <format attr="margin" value="0"/><format attr="margin-top" value="0"/>
      </zone-style>
    </zone>
    <zone h="37500" id="22" param="horz" type-v2="layout-flow" w="100000" x="0" y="25000">
      <zone forceUpdate="true" h="37500" id="23" type-v2="text" w="100000" x="0" y="25000">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_1</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="4"/><format attr="margin-left" value="8"/><format attr="margin-right" value="8"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
    </zone>
    <zone h="37500" id="9" layout-strategy-id="distribute-evenly" param="horz" type-v2="layout-flow" w="100000" x="0" y="62500">
      <zone forceUpdate="true" h="37500" id="12" type-v2="text" w="50000" x="0" y="62500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_2</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="4"/><format attr="margin-left" value="8"/><format attr="margin-bottom" value="8"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="37500" id="14" type-v2="text" w="50000" x="50000" y="62500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_3</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="4"/><format attr="margin-right" value="8"/><format attr="margin-bottom" value="8"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
    </zone>
  </zone>
</zones>
"""

# ── C5 template — Logo + Title, 5 KPIs, 2 left-stacked + 1 right-spanning ──
# Layout from Image 4: professional template with logo placeholder and 5 KPIs.
# Structure: Logo|Title → Filters → 5 KPIs → [Sheet1(left-top) | Sheet3(right-full)] → [Sheet2(left-bottom) | Sheet3 continues]
_C5_TEMPLATE_XML = """\
<zones>
  <zone h="100000" id="1" param="vert" type-v2="layout-flow" w="100000" x="0" y="0">
    <zone fixed-size="70" h="8750" id="2" is-fixed="true" param="horz" type-v2="layout-flow" w="100000" x="0" y="0">
      <zone forceUpdate="true" h="8750" id="6" type-v2="text" w="15000" x="0" y="0">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="12">LOGO PLACEHOLDER</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#d0d0d0"/><format attr="border-style" value="solid"/><format attr="border-width" value="1"/>
          <format attr="margin" value="4"/><format attr="margin-left" value="8"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="8750" id="5" type-v2="text" w="83666" x="15000" y="0">
        <formatted-text>
          <run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="20">TITLE PLACEHOLDER</run>
        </formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="4"/>
        </zone-style>
      </zone>
      <zone-style>
        <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
        <format attr="margin-right" value="8"/><format attr="margin-left" value="8"/>
        <format attr="background-color" value="#ffffff"/>
      </zone-style>
    </zone>
    <zone fixed-size="30" h="3750" id="3" is-fixed="true" param="horz" type-v2="layout-flow" w="100000" x="0" y="8750">
      <zone forceUpdate="true" h="3750" id="8" type-v2="text" w="98666" x="667" y="8750">
        <formatted-text>
          <run bold="true" fontalignment="1" fontcolor="#ffffff" fontsize="12">FILTERS PLACEHOLDER</run>
        </formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="4"/>
        </zone-style>
      </zone>
      <zone-style>
        <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
        <format attr="margin-right" value="8"/><format attr="margin-left" value="8"/>
        <format attr="background-color" value="#192f3e"/>
      </zone-style>
    </zone>
    <zone fixed-size="100" h="12500" id="16" is-fixed="true" layout-strategy-id="distribute-evenly" param="horz" type-v2="layout-flow" w="100000" x="0" y="12500">
      <zone forceUpdate="true" h="12500" id="17" type-v2="text" w="20000" x="0" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_1</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="4"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="8"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="20" type-v2="text" w="20000" x="20000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_2</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="4"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="4"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="21" type-v2="text" w="20000" x="40000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_3</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="4"/><format attr="margin-top" value="0"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="19" type-v2="text" w="20000" x="60000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_4</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="4"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="4"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone forceUpdate="true" h="12500" id="18" type-v2="text" w="20000" x="80000" y="12500">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">KPI_SLOT_5</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="0"/><format attr="margin-right" value="8"/><format attr="margin-bottom" value="4"/><format attr="margin-left" value="4"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
      <zone-style>
        <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
        <format attr="margin" value="0"/><format attr="margin-top" value="0"/>
      </zone-style>
    </zone>
    <zone fixed-size="1100" h="75000" id="9" is-fixed="true" param="horz" type-v2="layout-flow" w="100000" x="0" y="25000">
      <zone h="75000" id="10" layout-strategy-id="distribute-evenly" param="vert" type-v2="layout-flow" w="45000" x="0" y="25000">
        <zone forceUpdate="true" h="37500" id="12" type-v2="text" w="45000" x="0" y="25000">
          <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_1</run></formatted-text>
          <zone-style>
            <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
            <format attr="margin" value="4"/><format attr="margin-left" value="8"/>
            <format attr="background-color" value="#ffffff"/>
          </zone-style>
        </zone>
        <zone forceUpdate="true" h="37500" id="13" type-v2="text" w="45000" x="0" y="62500">
          <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_2</run></formatted-text>
          <zone-style>
            <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
            <format attr="margin" value="4"/><format attr="margin-bottom" value="8"/><format attr="margin-left" value="8"/>
            <format attr="background-color" value="#ffffff"/>
          </zone-style>
        </zone>
      </zone>
      <zone forceUpdate="true" h="75000" id="14" type-v2="text" w="55000" x="45000" y="25000">
        <formatted-text><run bold="true" fontalignment="1" fontcolor="#111e29" fontsize="15">SHEET_SLOT_3</run></formatted-text>
        <zone-style>
          <format attr="border-color" value="#000000"/><format attr="border-style" value="none"/><format attr="border-width" value="0"/>
          <format attr="margin" value="4"/><format attr="margin-right" value="8"/><format attr="margin-bottom" value="8"/>
          <format attr="background-color" value="#ffffff"/>
        </zone-style>
      </zone>
    </zone>
  </zone>
</zones>
"""

# Slot names in template order
_KPI_SLOTS = ["KPI_SLOT_1", "KPI_SLOT_2", "KPI_SLOT_3", "KPI_SLOT_4", "KPI_SLOT_5"]
_SHEET_SLOTS = ["SHEET_SLOT_1", "SHEET_SLOT_2", "SHEET_SLOT_3", "SHEET_SLOT_4"]

# Maximum sheet slots per template (for multi-dashboard splitting)
TEMPLATE_SHEET_CAPACITY = {
    "c2": 4,
    "c3": 4,
    "c4": 3,
    "c5": 3,
}


def _select_template_xml(n_kpis: int, n_charts: int) -> str:
    """Auto-select the best template based on dashboard content.

    Template selection rules:
    - C4 (logo, 4 KPI slots, 3 sheet slots): ≤4 KPIs AND ≤3 charts
    - C5 (logo, 5 KPI slots, 3 sheet slots): 5 KPIs AND ≤3 charts
    - C2 (4 KPI slots, 4 sheet slots): ≤4 KPIs AND >3 charts (fallback)
    - C3 (5 KPI slots, 4 sheet slots): 5 KPIs AND >3 charts (fallback)
    """
    if n_charts <= 3:
        # Use logo templates when fewer charts (more polished look)
        if n_kpis <= 4:
            return _C4_TEMPLATE_XML
        return _C5_TEMPLATE_XML
    # More charts → use 4-slot templates without logo
    if n_kpis <= 4:
        return _C2_TEMPLATE_XML
    return _C3_TEMPLATE_XML


def _resolve_filter_param(
    field_name: str, ws_name: str, field_registry: Any, editor: Any,
) -> str:
    """Resolve filter field to Tableau column reference."""
    if editor and ws_name:
        try:
            ws_el = editor._find_worksheet(ws_name)
            if ws_el is not None:
                for f_el in ws_el.findall(".//filter"):
                    col = f_el.get("column", "")
                    if field_name in col:
                        return col
        except (ValueError, AttributeError):
            pass
    if field_registry:
        try:
            ci = field_registry.parse_expression(field_name)
            return field_registry.resolve_full_reference(ci.instance_name)
        except (KeyError, ValueError):
            pass
    return field_name


def _compact_empty_layout_flow(template: etree._Element) -> None:
    """Remove empty layout-flow zones and redistribute their size to siblings.

    After unused ``SHEET_SLOT_N`` / ``KPI_SLOT_N`` placeholders are removed
    from the template, their parent ``<zone type-v2="layout-flow">`` may be
    left with no child ``<zone>`` elements.  Tableau still reserves that
    zone's full height/width on the canvas, which shows up as empty space
    in the rendered dashboard.

    This helper walks bottom-up, removes every empty layout-flow zone, and
    grows one sibling (the one facing the removed zone along the parent's
    layout axis) by the vacated size so total canvas coverage is preserved.
    Runs up to a few passes because removing one empty container can cause
    its parent to also become empty.
    """
    for _ in range(4):  # a few passes are sufficient for any C2–C5 template
        changed = False
        empties: list[etree._Element] = []
        for zone in template.iter("zone"):
            if zone.get("type-v2") != "layout-flow":
                continue
            # child zones only (skip zone-style / layout-cache / format)
            child_zones = [c for c in zone if c.tag == "zone"]
            if not child_zones:
                empties.append(zone)

        for zone in empties:
            parent = zone.getparent()
            if parent is None:
                continue
            siblings = [c for c in parent if c.tag == "zone" and c is not zone]
            try:
                zone_h = int(zone.get("h") or 0)
                zone_w = int(zone.get("w") or 0)
                zone_y = int(zone.get("y") or 0)
                zone_x = int(zone.get("x") or 0)
            except (TypeError, ValueError):
                zone_h = zone_w = zone_y = zone_x = 0
            parent.remove(zone)
            changed = True

            if not siblings:
                continue

            # Redistribute along the parent's flow axis.
            parent_is_vert = (parent.get("param") == "vert")
            if parent_is_vert and zone_h:
                # Grow the sibling(s) whose y is adjacent to the removed
                # zone (prefer the one *above*; fall back to any sibling).
                primary = None
                for sib in siblings:
                    try:
                        sy = int(sib.get("y") or 0)
                        sh = int(sib.get("h") or 0)
                    except (TypeError, ValueError):
                        continue
                    if sy + sh == zone_y:
                        primary = sib
                        break
                if primary is None:
                    primary = siblings[-1]
                try:
                    cur_h = int(primary.get("h") or 0)
                    primary.set("h", str(cur_h + zone_h))
                except (TypeError, ValueError):
                    pass
                # Grow all nested sheet zones inside `primary` proportionally.
                _grow_nested_zones(primary, extra_h=zone_h)
            elif not parent_is_vert and zone_w:
                primary = None
                for sib in siblings:
                    try:
                        sx = int(sib.get("x") or 0)
                        sw = int(sib.get("w") or 0)
                    except (TypeError, ValueError):
                        continue
                    if sx + sw == zone_x:
                        primary = sib
                        break
                if primary is None:
                    primary = siblings[-1]
                try:
                    cur_w = int(primary.get("w") or 0)
                    primary.set("w", str(cur_w + zone_w))
                except (TypeError, ValueError):
                    pass
                _grow_nested_zones(primary, extra_w=zone_w)

        if not changed:
            break

    # Second pass: any layout-flow container that now has exactly one child
    # where that child doesn't already fill the container should be grown
    # to fill.  This fixes the "half-empty row" case (e.g. only SHEET_SLOT_2
    # was filled and SHEET_SLOT_3 was removed — the surviving 50%-wide
    # child leaves the right half of the row blank).
    for zone in template.iter("zone"):
        if zone.get("type-v2") != "layout-flow":
            continue
        child_zones = [c for c in zone if c.tag == "zone"]
        if len(child_zones) != 1:
            continue
        child = child_zones[0]
        try:
            parent_h = int(zone.get("h") or 0)
            parent_w = int(zone.get("w") or 0)
            parent_x = int(zone.get("x") or 0)
            parent_y = int(zone.get("y") or 0)
            child_h = int(child.get("h") or 0)
            child_w = int(child.get("w") or 0)
        except (TypeError, ValueError):
            continue
        is_vert = zone.get("param") == "vert"
        if is_vert and child_h < parent_h:
            extra = parent_h - child_h
            child.set("h", str(parent_h))
            _grow_nested_zones(child, extra_h=extra)
        elif not is_vert and child_w < parent_w:
            extra = parent_w - child_w
            child.set("w", str(parent_w))
            # Child may need repositioning so it starts at the parent's left.
            child.set("x", str(parent_x))
            child.set("y", str(parent_y))
            _grow_nested_zones(child, extra_w=extra)


def _grow_nested_zones(
    container: etree._Element,
    extra_h: int = 0,
    extra_w: int = 0,
) -> None:
    """Propagate a height/width increase to every descendant zone.

    When we grow a container to absorb an empty sibling, any descendant
    ``<zone>`` whose own h / w spans the full extent of its parent needs
    to grow by the same amount so its content fills the new space.
    """
    if extra_h == 0 and extra_w == 0:
        return
    try:
        parent_h = int(container.get("h") or 0) - extra_h
        parent_w = int(container.get("w") or 0) - extra_w
    except (TypeError, ValueError):
        return
    for child in container:
        if child.tag != "zone":
            continue
        try:
            ch = int(child.get("h") or 0)
            cw = int(child.get("w") or 0)
        except (TypeError, ValueError):
            continue
        if extra_h and ch == parent_h:
            child.set("h", str(ch + extra_h))
            _grow_nested_zones(child, extra_h=extra_h)
        if extra_w and cw == parent_w:
            child.set("w", str(cw + extra_w))
            _grow_nested_zones(child, extra_w=extra_w)


def _swap_text_to_worksheet(zone: etree._Element, ws_name: str) -> None:
    """Convert a text placeholder zone into a worksheet zone.

    Removes type-v2, formatted-text; adds name + show-title.
    Preserves zone-style and all coordinates/attributes.
    """
    # Remove text-specific attributes and children
    if "type-v2" in zone.attrib:
        del zone.attrib["type-v2"]
    if "forceUpdate" in zone.attrib:
        del zone.attrib["forceUpdate"]
    ft = zone.find("formatted-text")
    if ft is not None:
        zone.remove(ft)

    # Add worksheet attributes
    zone.set("name", ws_name)
    zone.set("show-title", "true")

    # Insert layout-cache BEFORE zone-style for "Entire View" fit
    # This tells Tableau to scale the chart content to fill the zone
    zs = zone.find("zone-style")
    cache = etree.Element("layout-cache")
    cache.set("type-h", "scalable")
    cache.set("type-w", "scalable")
    if zs is not None:
        zone.insert(list(zone).index(zs), cache)
    else:
        zone.append(cache)


def _swap_text_to_filter(
    zone: etree._Element,
    filter_fields: list[dict[str, Any]],
    filter_worksheet: str,
    field_registry: Any,
    editor: Any,
    id_fn: Callable[[], int],
    rules: dict[str, Any] | None = None,
) -> None:
    """Replace the filter placeholder text zone with actual filter zones.

    The parent container already has the right styling (dark navy).
    We replace the single text child with N filter zone children.
    """
    parent = zone.getparent()
    if parent is None:
        return

    # Get the zone-style from the parent (container styling)
    parent_zs = parent.find("zone-style")

    # Remove the text placeholder zone
    parent.remove(zone)

    # Remove the parent's zone-style temporarily (must be re-added LAST)
    if parent_zs is not None:
        parent.remove(parent_zs)

    # Pre-resolve filter fields, skip any that can't be resolved
    valid_filters: list[tuple[str, str]] = []
    for f in filter_fields:
        field_name = f.get("field") or f.get("column", "")
        resolved = _resolve_filter_param(
            field_name, filter_worksheet, field_registry, editor,
        )
        # Only include filters that resolved to a proper datasource reference
        if resolved and "[" in resolved and "." in resolved:
            valid_filters.append((field_name, resolved))
        elif resolved and not resolved.startswith("["):
            # Try bracket-wrapping — Tableau may still accept it
            valid_filters.append((field_name, f"[{resolved}]"))

    if not valid_filters:
        # No valid filters — re-add parent zone-style and bail
        if parent_zs is not None:
            parent.append(parent_zs)
        return

    # Add filter zones.  Each filter is a clickable dropdown that must be
    # wide enough to show its label + value and tall enough to hit with a
    # mouse — Tableau collapses dropdowns below ~45 px.
    n = len(valid_filters)
    # Leave a small gap between filters so dropdowns don't touch.
    filter_gap = 200  # in 100000-unit width ≈ 2 px on a 1300-px canvas
    total_w = 98666 - filter_gap * max(0, n - 1)
    fw = total_w // n if n else 98666
    base_y = int(parent.get("y", "8750"))
    filter_h = int(parent.get("h", "3750"))

    # Apply mode determines filter scope within the dashboard.
    # Valid Tableau tokens:
    #   "all"       – apply to every worksheet on THIS dashboard that
    #                 uses the same datasource (the common "global" mode)
    #   "selected"  – apply only to the source worksheet
    # Default to "all" so the filter acts globally across the dashboard.
    filter_rules = ((rules or {}).get("layout", {}) or {}).get("filters", {}) or {}
    apply_mode = filter_rules.get("apply_mode", "all")
    filter_bg = filter_rules.get("zone_background", "#ffffff")
    filter_border = filter_rules.get("zone_border_color", "#d0d4d9")
    filter_border_width = str(int(filter_rules.get("zone_border_width", 1)))
    filter_margin = str(int(filter_rules.get("zone_margin", 6)))

    for fi, (field_name, resolved) in enumerate(valid_filters):
        fz = etree.SubElement(parent, "zone")
        fz.set("id", str(id_fn()))
        fz.set("type-v2", "filter")
        fz.set("name", filter_worksheet)
        fz.set("mode", "dropdown")
        fz.set("show-title", "true")
        fz.set("apply-to-worksheets", apply_mode)
        fz.set("x", str(667 + fi * (fw + filter_gap)))
        fz.set("y", str(base_y))
        fz.set("w", str(fw))
        fz.set("h", str(filter_h))
        fz.set("param", resolved)

        # Filter zone-style: visible border + generous margin so the
        # dropdown reads as a clickable card, not a line of text.
        zs = etree.SubElement(fz, "zone-style")
        for attr, val in [
            ("border-color", filter_border),
            ("border-style", "solid"),
            ("border-width", filter_border_width),
            ("margin", filter_margin),
            ("background-color", filter_bg),
        ]:
            fmt = etree.SubElement(zs, "format")
            fmt.set("attr", attr)
            fmt.set("value", val)

    # Re-add parent zone-style LAST
    if parent_zs is not None:
        parent.append(parent_zs)


def _expand_filter_row(
    template: etree._Element, rules: dict[str, Any] | None,
) -> int:
    """Ensure the filter bar is tall enough to be visible + clickable.

    All four layout templates (C2/C3/C4/C5) historically ship a filter
    container at ``fixed-size=30 / h=3750`` (~30 px on a 1300-px canvas).
    That collapses Tableau's default dropdown styling below readability,
    leaving the filter strip as a dark sliver users can't click.

    This pass:

    1. Grows the filter container to ``layout.filters.min_height_px``
       (default 55 px / 5.5% of canvas height).
    2. Shifts every zone sitting below the filter bar down by the same
       amount so the KPI row doesn't collide.
    3. Shrinks the chart container (the last fixed-size child of root)
       by the same delta so the total dashboard height stays at 100 000
       proportional units.  Nested chart slots are scaled proportionally.

    Returns the ``delta_h`` (in proportional units) that was applied; 0
    if no change.  Called from ``_build_from_template_xml`` right after
    the template is parsed.
    """
    filter_cfg = ((rules or {}).get("layout", {}) or {}).get("filters", {}) or {}
    min_px = int(filter_cfg.get("min_height_px", 55))

    # Locate the filter container (id="3" in every template; secondary
    # fallback is a <zone> that contains a FILTERS PLACEHOLDER descendant).
    filter_zone = None
    for z in template.iter("zone"):
        if z.get("id") == "3":
            filter_zone = z
            break
    if filter_zone is None:
        for z in template.iter("zone"):
            for ft in z.iter("formatted-text"):
                run = ft.find("run")
                if run is not None and (run.text or "").strip() == "FILTERS PLACEHOLDER":
                    filter_zone = z
                    break
            if filter_zone is not None:
                break
    if filter_zone is None:
        return 0

    try:
        cur_fs = int(filter_zone.get("fixed-size", "30"))
        cur_h = int(filter_zone.get("h", "3750"))
        filter_y = int(filter_zone.get("y", "0"))
    except (TypeError, ValueError):
        return 0
    if cur_fs <= 0 or cur_fs >= min_px:
        return 0  # already adequate — don't waste chart space

    delta_fs = min_px - cur_fs
    # Preserve ratio between fixed-size (px) and h (100000-proportional).
    new_h = int(cur_h * min_px / cur_fs)
    delta_h = new_h - cur_h
    filter_bottom = filter_y + cur_h

    # 1) Grow the filter container itself.
    filter_zone.set("fixed-size", str(min_px))
    filter_zone.set("h", str(new_h))
    for ch in filter_zone.iter("zone"):
        if ch is filter_zone:
            continue
        try:
            ch_h = int(ch.get("h", str(cur_h)))
        except (TypeError, ValueError):
            continue
        if ch_h == cur_h:
            ch.set("h", str(new_h))

    # 2) Shift every OTHER zone whose y sits at or below the filter
    #    bottom.  Children of filter_zone are already handled above.
    filter_descendants = set(id(z) for z in filter_zone.iter("zone"))
    for z in template.iter("zone"):
        if id(z) in filter_descendants:
            continue
        try:
            z_y = int(z.get("y", "0"))
        except (TypeError, ValueError):
            continue
        if z_y >= filter_bottom:
            z.set("y", str(z_y + delta_h))

    # 3) Reclaim the delta from the zones below the filter so the
    #    dashboard still fits the 100 000-unit root.
    #
    #    Case A — c3 template: the last root child is an `is-fixed`
    #             chart container with h ~= 75 000.  Shrink it + all
    #             descendants proportionally.
    #    Case B — c2/c4 templates: the chart rows are non-fixed
    #             direct children of root, each h ~= 37 500.  Shrink
    #             each one by half the delta (or proportionally to
    #             their share) so the total collapses by delta_h.
    root_zone = template.find("zone")
    if root_zone is not None:
        fixed_chart_container = None
        nonfixed_chart_rows: list[etree._Element] = []
        for child in root_zone.findall("zone"):
            try:
                child_h = int(child.get("h", "0"))
                child_y = int(child.get("y", "0"))
            except (TypeError, ValueError):
                continue
            # Only rows BELOW the (original) filter qualify.
            if child_y < filter_bottom:
                continue
            if child.get("is-fixed") == "true" and child_h >= 30000:
                fixed_chart_container = child  # last one wins
            elif child.get("is-fixed") != "true":
                nonfixed_chart_rows.append(child)

        if fixed_chart_container is not None:
            try:
                cc_fs = int(fixed_chart_container.get("fixed-size", "0"))
                cc_h = int(fixed_chart_container.get("h", "0"))
            except (TypeError, ValueError):
                cc_fs = cc_h = 0
            if cc_h > delta_h:
                new_cc_h = cc_h - delta_h
                fixed_chart_container.set("h", str(new_cc_h))
                if cc_fs > delta_fs:
                    fixed_chart_container.set("fixed-size", str(cc_fs - delta_fs))
                scale = new_cc_h / cc_h
                for ch in fixed_chart_container.iter("zone"):
                    if ch is fixed_chart_container:
                        continue
                    try:
                        ch_h = int(ch.get("h", "0"))
                    except (TypeError, ValueError):
                        continue
                    ch.set("h", str(int(ch_h * scale)))
        elif nonfixed_chart_rows:
            # Shrink each non-fixed row proportionally.  Remaining
            # slots below the filter must together lose delta_h units.
            total = sum(int(r.get("h", "0")) for r in nonfixed_chart_rows) or 1
            cumulative_shift = 0
            for r in nonfixed_chart_rows:
                try:
                    r_h = int(r.get("h", "0"))
                except (TypeError, ValueError):
                    continue
                row_delta = int(delta_h * r_h / total)
                new_r_h = max(0, r_h - row_delta)
                scale = new_r_h / r_h if r_h else 1
                r.set("h", str(new_r_h))
                # Push this row's y up by anything previous rows lost
                # so they stack cleanly.
                try:
                    r.set("y", str(int(r.get("y", "0")) - cumulative_shift))
                except (TypeError, ValueError):
                    pass
                cumulative_shift += row_delta
                # Scale descendants' h to match.
                for ch in r.iter("zone"):
                    if ch is r:
                        continue
                    try:
                        ch_h = int(ch.get("h", "0"))
                    except (TypeError, ValueError):
                        continue
                    ch.set("h", str(int(ch_h * scale)))

    return delta_h


def _apply_rules_to_template(template: etree._Element, rules: dict[str, Any]) -> None:
    """Patch template zones with dashboard rules (KPI fonts, title, filter bar, backgrounds).

    Modifies the parsed template XML in-place so that:
    - KPI cards use the font size, color, and row height from ``rules['kpi']``
    - Title bar uses font settings from ``rules['layout']['title']``
    - Filter bar uses background/font settings from ``rules['layout']['filters']``
    - Card backgrounds use the color from ``rules['layout']['card_background']``
    """
    kpi_cfg = rules.get("kpi", {})
    layout_cfg = rules.get("layout", {})
    title_cfg = layout_cfg.get("title", {})
    filter_cfg = layout_cfg.get("filters", {})

    kpi_font_size = str(kpi_cfg.get("font_size", 15))
    kpi_font_color = kpi_cfg.get("font_color", "#111e29")
    kpi_bold = kpi_cfg.get("bold", True)
    kpi_row_height = kpi_cfg.get("row_height")

    title_font_size = str(title_cfg.get("font_size", 20))
    title_font_color = title_cfg.get("font_color", "#111e29")
    title_bold = title_cfg.get("bold", True)

    filter_bg = filter_cfg.get("background_color", "#192f3e")
    filter_font_color = filter_cfg.get("font_color", "#ffffff")
    filter_font_size = str(filter_cfg.get("font_size", 12))

    card_bg = layout_cfg.get("card_background", "#ffffff")

    for zone in template.iter("zone"):
        ft = zone.find("formatted-text")
        if ft is None:
            continue
        run = ft.find("run")
        if run is None or run.text is None:
            continue
        slot_text = run.text.strip()

        # Patch KPI slot font settings
        if slot_text.startswith("KPI_SLOT_"):
            run.set("fontsize", kpi_font_size)
            run.set("fontcolor", kpi_font_color)
            run.set("bold", "true" if kpi_bold else "false")
            # Update card background
            _set_zone_bg(zone, card_bg)

        # Patch title font settings
        if slot_text == "TITLE PLACEHOLDER":
            run.set("fontsize", title_font_size)
            run.set("fontcolor", title_font_color)
            run.set("bold", "true" if title_bold else "false")

        # Patch filter bar font settings
        if slot_text == "FILTERS PLACEHOLDER":
            run.set("fontsize", filter_font_size)
            run.set("fontcolor", filter_font_color)

        # Patch sheet slot card backgrounds
        if slot_text.startswith("SHEET_SLOT_"):
            _set_zone_bg(zone, card_bg)

    # Patch filter container background (zone id="3" in all templates)
    for zone in template.iter("zone"):
        if zone.get("id") == "3":
            zone_style = zone.find("zone-style")
            if zone_style is not None:
                for fmt in zone_style.findall("format"):
                    if fmt.get("attr") == "background-color":
                        fmt.set("value", filter_bg)
            break

    # Patch KPI container row height (zone id="16" in all templates)
    if kpi_row_height:
        for zone in template.iter("zone"):
            if zone.get("id") == "16":
                zone.set("fixed-size", str(kpi_row_height))
                h_val = int(kpi_row_height * 100000 / 800)  # approximate Tableau units
                zone.set("h", str(h_val))
                break


def _set_zone_bg(zone: etree._Element, color: str) -> None:
    """Set the background-color format on a zone's zone-style."""
    zone_style = zone.find("zone-style")
    if zone_style is None:
        return
    for fmt in zone_style.findall("format"):
        if fmt.get("attr") == "background-color":
            fmt.set("value", color)
            return
    # Add background-color format if not present
    fmt = etree.SubElement(zone_style, "format")
    fmt.set("attr", "background-color")
    fmt.set("value", color)


def build_c3_zones(
    zones_el: etree._Element,
    id_fn: Callable[[], int],
    *,
    title: str = "Dashboard",
    kpi_names: list[str] | None = None,
    chart_names: list[str] | None = None,
    filters: list[dict[str, Any]] | None = None,
    filter_worksheet: str = "",
    field_registry: Any = None,
    editor: Any = None,
    rules: dict[str, Any] | None = None,
) -> None:
    """Build C3 template by copying Tableau-native XML and swapping names.

    This is the Template TWB Swap approach — the gold standard:
    1. Parse the exact C3 template XML (generated by Tableau Desktop)
    2. Swap text placeholder zones → real worksheet zones (name only)
    3. Swap filter placeholder → real filter zones
    4. Set title text
    5. Re-number zone IDs
    Never touch coordinates, margins, or structure.
    """
    kpi_names = kpi_names or []
    chart_names = chart_names or []
    filters = filters or []

    # Auto-select the best template based on content
    template_xml = _select_template_xml(len(kpi_names), len(chart_names))
    template = etree.fromstring(template_xml)

    # Apply YAML rules to template (font size, row height, etc.)
    if rules:
        _apply_rules_to_template(template, rules)

    # Grow the filter bar so filters are visibly clickable (default 55 px).
    # Every template ships with a 30-px filter strip that collapses the
    # dropdown below Tableau's minimum readable size; this pass re-flows
    # the zones below it to recover the height without overflowing.
    _expand_filter_row(template, rules)

    # Build slot→name mappings
    kpi_map: dict[str, str] = {}
    for i, name in enumerate(kpi_names):
        if i < len(_KPI_SLOTS):
            kpi_map[_KPI_SLOTS[i]] = name

    sheet_map: dict[str, str] = {}
    for i, name in enumerate(chart_names):
        if i < len(_SHEET_SLOTS):
            sheet_map[_SHEET_SLOTS[i]] = name

    # Find all zones and process by slot name
    unused_kpi_slots: list[etree._Element] = []
    unused_sheet_slots: list[etree._Element] = []

    for zone in template.iter("zone"):
        ft = zone.find("formatted-text")
        if ft is None:
            continue
        run = ft.find("run")
        if run is None or run.text is None:
            continue
        slot_text = run.text.strip()

        # Logo placeholder — leave as-is (user can replace with image)
        if slot_text == "LOGO PLACEHOLDER":
            continue

        # Title swap
        if slot_text == "TITLE PLACEHOLDER":
            run.text = title or "Dashboard"
            continue

        # Filter swap
        if slot_text == "FILTERS PLACEHOLDER":
            if filters and filter_worksheet:
                _swap_text_to_filter(
                    zone, filters, filter_worksheet,
                    field_registry, editor, id_fn,
                    rules=rules,
                )
            continue

        # KPI swap
        if slot_text in _KPI_SLOTS:
            if slot_text in kpi_map:
                _swap_text_to_worksheet(zone, kpi_map[slot_text])
            else:
                unused_kpi_slots.append(zone)
            continue

        # Sheet swap
        if slot_text in _SHEET_SLOTS:
            if slot_text in sheet_map:
                _swap_text_to_worksheet(zone, sheet_map[slot_text])
            else:
                unused_sheet_slots.append(zone)
            continue

    # Remove unused KPI slots (if fewer KPIs than 5)
    for z in unused_kpi_slots:
        parent = z.getparent()
        if parent is not None:
            parent.remove(z)

    # Remove unused sheet slots (if fewer charts than 4)
    for z in unused_sheet_slots:
        parent = z.getparent()
        if parent is not None:
            parent.remove(z)

    # Compact empty layout-flow containers left behind by the removals above.
    # When e.g. only SHEET_SLOT_1 is filled, the second horizontal row (that
    # would have hosted SHEET_SLOT_2 + SHEET_SLOT_3) is now an empty
    # layout-flow zone taking 37.5% of the canvas height — shown in the UI
    # as dead space under the one chart.  Redistribute that height back to
    # the remaining sibling(s) so the dashboard uses the whole canvas.
    _compact_empty_layout_flow(template)

    # If no KPIs at all, remove the KPI container row
    if not kpi_names:
        for zone in template.iter("zone"):
            if zone.get("id") == "16":  # KPI container
                parent = zone.getparent()
                if parent is not None:
                    parent.remove(zone)
                break

    # If no filters, remove the filter container row
    if not filters or not filter_worksheet:
        for zone in template.iter("zone"):
            if zone.get("id") == "3":  # Filter container
                parent = zone.getparent()
                if parent is not None:
                    parent.remove(zone)
                break

    # Re-number all zone IDs to be unique using id_fn
    for zone in template.iter("zone"):
        zone.set("id", str(id_fn()))

    # Copy template content into the target zones element
    root_zone = template.find("zone")
    if root_zone is not None:
        zones_el.append(root_zone)

    print(f"[C3-LAYOUT] Built: title={title}, {len(kpi_names)} KPIs, "
          f"{len(chart_names)} charts, {len(filters)} filters")
    logger.info(
        "Built C3 layout: title=%s, %d KPIs, %d charts, %d filters",
        title, len(kpi_names), len(chart_names), len(filters),
    )
